### ISSUE TITLE
Upgrade to latest Tailwind v3

### ISSUE THREAD

**Issue by plexus** [green-coder/girouette#79]
The README mentions tailwind 2.0.2, the latest release is 3.0.17.

What would it take to upgrade girouette? Would financial support help?

**Comment by jamesnvc** [comment]
I’ve actually been talking about this with my business partner and have been considering starting on the effort, if it’s a direction @green-coder wants to go in

**Comment by plexus** [comment]
That's great to hear @jamesnvc, it's definitely a concern we've heard from people considering using Ornament. So we'd be willing to consider supporting someone via the lambda island open collective, or to have someone from Gaiwan help with this.

**Comment by green-coder** [comment]
I need more time to think about it (It's family time here in Taiwan - Lunar New Year).

Maybe an implementation compatible with Tailwind `v3.*.*` should be in a separate namespace `girouette.tw3` if its grammar conflicts with the component's rules already implemented in the namespace`girouette.tw`.

**Comment by jamesnvc** [comment]
> It's family time here in Taiwan - Lunar New Year

Enjoy your holidays!

>  if its grammar conflicts with the component's rules already implemented

From a brief look, I think that most of it can be done purely additively -- the biggest difference I see is Tailwind's square-bracket syntax for arbitrary values.

**Comment by green-coder** [comment]
@plexus It's important for me to fully understand what the request actually is:

Is it that people want to have full compatibility with Tailwind v3?
**- or -**
Is it that they want to have the same features by fear of missing something important?

**Comment by plexus** [comment]
I think the main reasons are

- being able to copy-paste tailwind components into a girouette code base
- leveraging existing familiarity with the api

I agree that if there are breaking changes that some kind of namespacing is in order

**Comment by green-coder** [comment]
The grammar described in namespace `girouette.tw` was created from the documentation of Tailwind v2.0.2 which was the latest at that time, and I added a lot of extensions and additions where it looked like a good idea to do so. I knew that it meant to run into incompatibilities with future versions later on, but I did it anyway because Tailwind was limited and there was a need to innovate.

I want to leave this namespace as it is for now and use a namespace `girouette.tw3` for implementing the docs of Tailwind v3. The goal for this separate grammar is to be **100% compatible with the official doc by default**, so we can copy/paste snippets as strings and have them work.

Some components might be referenced from `girouette.tw` when they are exactly the same, but they should be duplicated otherwise.

Some changes could be added to Girouette later to let the user customize the grammar in places where it might be handy, for example like replacing the `[` and `]` by `<` and `>` to use keywords instead of strings, or to support additional color representation formats.

Financial support would be appreciated, it would have a symbolic importance for me as it would mark the first time someone pays me for working on an open source project. James Cash started implementing the missing components already, he might finish soon and you could use his branch if your need is urgent. It might take me some time to have the same functionalities in the `master` branch because the same amount of work will have to be done either as a code review, refactoring, or rewriting - I will know once I start, and it might be only during the weekends or late at night bit by bit.

**Comment by plexus** [comment]
> it would have a symbolic importance for me as it would mark the first time someone pays me for working on an open source project

Have you ever asked for funding? Is there anything set up that you can point people at like a Patreon, kofi, or PayPal link?

**Comment by green-coder** [comment]
I never asked for funding and never considered about it. I still have to setup a payment system which would work in Taiwan. @jamesnvc Did a lot of work on the feature, if he is interested I propose to send him half of the funding.

> I want to leave this namespace as it is for now and use a namespace girouette.tw3 for implementing the docs of Tailwind v3.

I changed my mind here: I will probably merge most of his commits in namespace `girouette.tw` as long as it looks compatible, and then create a strictly compatible Tailwind v3 grammar in `girouette.tw3`.

**Comment by jamesnvc** [comment]
> @jamesnvc Did a lot of work on the feature, if he is interested I propose to send him half of the funding.

That would be extremely appreciated and would also be my first time being compensated for open-source work :)

**Comment by green-coder** [comment]
Note to self: the params for the shadows are different in v2 and v3.
